apiVersion: v1
kind: ConfigMap
metadata:
  name: app-service-config
data:
  APP_PORT: "{{ .Values.deployment.port }}"
  LOG_LEVEL: "{{ .Values.deployment.loglevel }}"
  APP_SERVICE_NAME: {{ .Release.Name }}