apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:  # We dont need to worry about converting to base64
  DB_USER: {{ .Values.database.user }}
  DB_PASSWORD: {{ .Values.database.pass }}
  DB_NAME: {{ .Values.database.name }}

  DB_HOST: {{ .Values.database.host }}
  DB_PORT: "{{ .Values.database.port }}"
  DB_TIMEOUT: "{{ .Values.database.timeout }}"
  DB_POOLMAX: "{{ .Values.database.poolmax }}"
  SERVICE_PORT: "{{ .Values.deployment.port }}"
